plugin:
    name: 'nielsvandendries.rssreader::lang.plugin.name'
    description: 'nielsvandendries.rssreader::lang.plugin.description'
    author: 'Niels van den Dries'
    icon: oc-icon-rss
    homepage: 'https://nvandendries.dev'
permissions:
    manager:
        tab: 'nielsvandendries.rssreader::lang.plugin.name'
        label: Manager
navigation:
    main-menu-item-rssreader:
        label: 'Rss Reader'
        url: nielsvandendries/rssreader/rsssources
        icon: icon-rss
        permissions:
            - manager
